#version 450

layout (local_size_x = 8) in;
layout (local_size_y = 8) in;

layout(set = 0, binding = 0) uniform sampler2D inImage;
layout (set = 0, binding = 1, rgba8) uniform writeonly image2D outImage;

layout(push_constant) uniform ImageInfo {
    int width;
    int height;
} info;

void main() {
    uvec2 ids = gl_GlobalInvocationID.xy;
    if(ids.x < 0 || ids.y < 0 || ids.x >= info.width || ids.y >= info.height) return;

    imageStore(outImage, ivec2(ids), vec4(1.0, 0.0, 0.0, 1.0));
}